services:
  # Your n8n application service (e.g., a web server)
  server_n8n:
    image: n8nio/n8n
    container_name: cont_n8n
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=${EXTERNAL_IP}
      - WEBHOOK_URL=${EXTERNAL_IP}
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    networks:
      - n8n_network
    volumes:
      - ${PWD}/vol_n8n:/home/node/.n8n
    restart: unless-stopped

  # Cloudflare Tunnel service
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TZ=Asia/Ho_Chi_Minh
    networks:
      - n8n_network
    depends_on:
      - server_n8n
    # Uncomment if using a credentials file instead of a token:
    # volumes:
    #   - ./tunnel/credentials.json:/etc/cloudflared/credentials.json
    restart: unless-stopped

networks:
  n8n_network:
    driver: bridge

